### ISSUE TITLE
Fix macros/componentParametricCuboid

### ISSUE THREAD

**Issue by samfallible** [samfallible/freeCAD#1]
[macros/componentParametricCuboid](https://github.com/samfallible/freeCAD/tree/main/macros/componentParametricCuboid)
User reported critical errors

File "C:/Users/root/Downloads/componentRectangularPrism.FCMacro", line 36, in <module>
    geoList.append(Part.LineSegment(App.Vector(-1.002072,0.919122,0),App.Vector(1.089203,0.919122,0)))
<class 'NameError'>: name 'Part' is not defined
15:53:48  Traceback (most recent call last):
  File "C:/Users/root/AppData/Roaming/FreeCAD/Macro/componentRectangularPrism.FCMacro", line 97, in <module>
    App.getDocument("ParametricRectangle").saveAs(u"C:/Users/18055/Documents/freeCAD/20241110wormBinParametric/rectangularPrism.FCStd")
<class 'OSError'>: Failed to open file: C:/Users/18055/Documents/freeCAD/20241110wormBinParametric/rectangularPrism.FCStd.8b3f607f-bb4c-419b-a27a-6de9b687e274

**Comment by samfallible** [comment]
[ffcc3e0](https://github.com/samfallible/freeCAD/commit/ffcc3e0e80febadc08944363c8b6880bb224ac0b) - Refactor removing save behavior and using different function calls throughout.

**Comment by samfallible** [comment]
blocked until tested
